# Generated by Django 2.0 on 2017-12-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='descriptions',
            field=models.TextField(default='description default text'),
        ),
    ]
