# Generated by Django 2.0 on 2017-12-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='descriptions',
            field=models.TextField(default='true'),
        ),
    ]
