# Generated by Django 2.0 on 2017-12-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20171215_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='descriptions',
            field=models.TextField(default='default text value'),
        ),
    ]
